### ISSUE TITLE
Query - ReactJS - Server side rendering

### ISSUE THREAD

**Issue by sabha** [adobe/target-nodejs-sdk-samples#1]
Thanks for the JS package. We have a react app and the page is rendered on the server side. 

We are Trying to render different react components (A or B or C) based on the AB test response , please assist with a code sample.

For 
- content: "{"activityId":164422,"experienceId":"A"}" - React Component A - 25%
- content: "{"activityId":164422,"experienceId":"B"}" - React Component B - 25%
- content: "{"activityId":164422,"experienceId":"C"}" - React Component C - 50%
 
Since we have Redux so we will store the experienceId in the store and render the respective react component which team have build already.

**Comment by hariKarthic** [comment]
Just curious but did this  help ? https://github.com/Adobe-Marketing-Cloud/target-atjs-extensions/tree/master/react/component#target-react-component

**Comment by XDex** [comment]
Closing for now, please open another issue if the question is still relevant for the newly published Node.js SDK v1.x samples.
Thanks!
