### ISSUE TITLE
Next.js demo not working with latest sdk version

### ISSUE THREAD

**Issue by tinavanschelt** [adobe/target-nodejs-sdk-samples#17]
The [next-server-side-rendering-demo](https://github.com/adobe/target-nodejs-sdk-samples/tree/master/next-server-side-rendering-demo) uses `"@adobe/target-nodejs-sdk": "^1.0.3"`, when we upgrade the node sdk to `"^2.1.0"` the `getOffers()` request keeps returning `Target: Error prefetching offers:  Error: Bad Request`.

We would prefer to use the latest version of the sdk. Are there any plans to upgrade the demo or any documentation available for bumping v1 to v2?

Thank you.

**Comment by jasonwaters** [comment]
Hi @tinavanschelt, Thank you for reporting this issue.  It was not an issue with the Target Node.js SDK, it was an issue with the nextjs sample implementation code.  I have updated the sample to be fully functional.  Please pull the latest.

Cheers 🍻
