### ISSUE TITLE
Invalid request: Mbox host '' is not authorized

### ISSUE THREAD

**Issue by taniksyal** [adobe/target-nodejs-sdk-samples#2]
Getting the below error when trying to connect to our own Adobe target instance.
Invalid request: Mbox host '' is not authorized
Updated the config as below:
client: "&lt;clientname&gt;,
organizationId: "orgId",
serverDomain: "&lt;clientname&gt;.tt.omtrdc.net",

Also updated mbox in the payload to the mbox needed.

Not sure what is missing.

Thanks for your help.

**Comment by webstrategiconsultant** [comment]
Login to your target account go to set up>>hosts>>settings and under  Enable Authorized Hosts for Content Delivery white list your domain

**Comment by XDex** [comment]
@taniksyal Has the above suggestion solved the issue?
Closing for now, please open another issue if the question is still relevant for the newly published Node.js SDK v1.x samples.
Thanks!
